---
collections:
  - ansible.posix
  - ansible.windows
  - awx.awx
  - azure.azcollection
  - ovirt.ovirt
  - redhatinsights.insights
  - theforeman.foreman
  - community.general
  - ansible.network
  - ansible.netcommon
  - ansible.utils
  - ansible.security
  - tmichett.gls_collection_demo
  - redhat_cop.ah_configuration
  - redhat_cop.controller_configuration
  - redhat_cop.ee_utilities
  - redhat_cop.aap_utilities
  - chocolatey.chocolatey